USE sakila;

-- List the number of films per category.

SELECT category.name, COUNT(film.film_id)
FROM category
INNER JOIN film_category 
USING (category_id)
INNER JOIN film 
USING (film_id)
GROUP BY category.category_id, category.name;

-- Retrieve the store ID, city, and country for each store.

SELECT store.store_id, city.city, country.country
FROM store
INNER JOIN address 
USING (address_id)
INNER JOIN city 
USING (city_id)
INNER JOIN country 
USING (country_id);

-- Calculate the total revenue generated by each store in dollars.

SELECT store.store_id, SUM(payment.amount) AS revenue_generated
FROM store
INNER JOIN staff 
USING (store_id)
INNER JOIN payment 
USING (staff_id)
GROUP BY store.store_id;

-- Determine the average running time of films for each category.

SELECT category.name, AVG(film.length) AS average_running_time
FROM category
INNER JOIN film_category 
USING (category_id)
INNER JOIN film 
USING (film_id)
GROUP BY category.category_id, category.name;